name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0
      with:
        channel: beta
    - name: Publish Build
      run: |
        flutter config --enable-web
        flutter pub get
        flutter build web --release
        cd build/web
        rm -rf .git
        git init
        git remote add origin git@github.com:GameHolics/excel_parser.git
        git checkout -b gh-pages
        git add --all && git commit -m "update"
        git push origin gh-pages -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
