name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web --release
    - run: git config --global --add user.name AllenDK
    - run: git config --global --add user.email allendk@foxmail.com
    - run: cd build/web
    - run: git init
    - run: git remote add origin git@github.com:GameHolics/excel_parser.git
    - run: git checkout -b gh-pages
    - run: git add --all
    - run: git commit -m "update"
    - run: git push origin gh-pages -f
